title: JayGlow Cyber
description: Advanced Malware Analysis, Detection Engineering, and Solo Purple Teaming Research.
url: "jayglowcyber.com"
baseurl: ""

markdown: kramdown
permalink: /research/:title/
